--Create Table
CREATE SEQUENCE DW_TEMPCOMPATIBILITYDETAILS_SEQ;
CREATE TABLE DW_TEMPCOMPATIBILITYDETAILS (
TEMPCOMPATIBILITYDETAILS_ID INT NOT NULL,
TEMPID	 INT NOT NULL, 
BRANCHID	VARCHAR2(20 BYTE) NOT NULL,
COMPATIBILITY	VARCHAR2(5 BYTE) NOT NULL,
PRIMARY KEY(TEMPCOMPATIBILITYDETAILS_ID)
);
--Transferring
declare
Cursor c_client is
SELECT TEMPID,
BRANCHID,
COMPATIBILITY from ST_TEMPCOMPATIBILITYDETAILS;
begin
for c_rec in c_client loop
insert into DW_TEMPCOMPATIBILITYDETAILS values(DW_TEMPCOMPATIBILITYDETAILS_SEQ.nextval, c_rec.TEMPID, c_rec.BRANCHID, c_rec.COMPATIBILITY);

end loop;
end;
--DEFAULT SETTINGS
ALTER TABLE DW_TEMPCOMPATIBILITYDETAILS MODIFY COMPATIBILITY DEFAULT '0';
