--Create Table
CREATE TABLE DW_TEMP(
TEMPID	INT NOT NULL,
TITLE	VARCHAR(10) NOT NULL,
FIRST_NAME	VARCHAR2(20) NOT NULL,
LAST_NAME	VARCHAR2(20) NOT NULL,
ADDRESS_LINE_1	VARCHAR2(40) NOT NULL,
ADDRESS_LINE_2	VARCHAR2(40) NOT NULL,
TOWN		VARCHAR2(20) NOT NULL,
COUNTY		VARCHAR2(20) NOT NULL,
POSTCODE	VARCHAR2(20) NOT NULL,
TEL_HOME		VARCHAR2(20) NOT NULL,
FAX_HOME		VARCHAR2(20) NOT NULL,
TEL_WORK		VARCHAR2(20) NOT NULL,
FAX_WORK		VARCHAR2(20) NOT NULL,
EMAIL 			VARCHAR(30) NOT NULL,
MOBILE_PHONE		VARCHAR2(20) NOT NULL,
APP_SENT	DATE NOT NULL,
GENDER		VARCHAR2(20) NOT NULL,
CURRENT_STATUS		VARCHAR2(20) NOT NULL,
DATE_OF_BIRTH		VARCHAR2(20) NOT NULL,
NATIONALITY	VARCHAR2(20) NOT NULL,
USE_OF_CAR	VARCHAR2(20) NOT NULL,
QUALIFICATION_YEAR		VARCHAR2(20) NOT NULL,
QUALIFICATION_PLACE		VARCHAR2(20) NOT NULL,
TYPE_OF_COVER_PREFERRED		VARCHAR2(20) NOT NULL,
MONDAY_AM	VARCHAR2(5) NOT NULL,
MONDAY_PM	VARCHAR2(5) NOT NULL,
TUESDAY_AM	VARCHAR2(5) NOT NULL,
TUESDAY_PM	VARCHAR2(5) NOT NULL,
WEDNESDAY_AM	VARCHAR2(5) NOT NULL,
WEDNESDAY_PM	VARCHAR2(5) NOT NULL,
THURSDAY_AM	VARCHAR2(5) NOT NULL,
THURSDAY_PM	VARCHAR2(5) NOT NULL,
FRIDAY_AM	VARCHAR2(5) NOT NULL,
FRIDAY_PM	VARCHAR2(5) NOT NULL,
SATURDAY_AM	VARCHAR2(5) NOT NULL,
TEMP_REGISTRATION_STATUS	VARCHAR2(20) NOT NULL,
APP_RECEIVED	VARCHAR2(5) NOT NULL,
TEMPSTATUS	VARCHAR2(5) NOT NULL,
PRIMARY KEY(TEMPID)
);

--Transferring
declare
Cursor c_client is
SELECT TEMP_ID,
TITLE,
FIRST_NAME,
LAST_NAME,
ADDRESS_LINE_1,
ADDRESS_LINE_2,
TOWN,
COUNTY,
POSTCODE,
TEL_HOME,
FAX_HOME,
TEL_WORK,
FAX_WORK,
EMAIL,
MOBILE_PHONE,
DATE_SENT,
GENDER,
CURRENT_STATUS,
DATE_OF_BIRTH,
NATIONALITY,
USE_OF_A_CAR,
QUALIFICATION_YEAR,
QUALIFICATION_PLACE,
TYPE_OF_COVER_PREFERRED,
MONDAY_AM,
MONDAY_PM,
TUESDAY_AM,
TUESDAY_PM,
WEDNESDAY_AM,
WEDNESDAY_PM,
THURSDAY_AM,
THURSDAY_PM,
FRIDAY_AM,
FRIDAY_PM,
SATURDAY_AM,
TEMP_REGISTRATION_STATUS,
DATE_RECEIVED,
TEMPSTATUS from ST_TEMP;
begin
for c_rec in c_client loop
insert into DW_TEMP values(
c_rec.TEMP_ID,
c_rec.TITLE,
c_rec.FIRST_NAME,
c_rec.LAST_NAME,
c_rec.ADDRESS_LINE_1,
c_rec.ADDRESS_LINE_2,
c_rec.TOWN,
c_rec.COUNTY,
c_rec.POSTCODE,
c_rec.TEL_HOME,
c_rec.FAX_HOME,
c_rec.TEL_WORK,
c_rec.FAX_WORK,
c_rec.EMAIL,
c_rec.MOBILE_PHONE,
c_rec.DATE_SENT,
c_rec.GENDER,
c_rec.CURRENT_STATUS,
c_rec.DATE_OF_BIRTH,
c_rec.NATIONALITY,
c_rec.USE_OF_A_CAR,
c_rec.QUALIFICATION_YEAR,
c_rec.QUALIFICATION_PLACE,
c_rec.TYPE_OF_COVER_PREFERRED,
c_rec.MONDAY_AM,
c_rec.MONDAY_PM,
c_rec.TUESDAY_AM,
c_rec.TUESDAY_PM,
c_rec.WEDNESDAY_AM,
c_rec.WEDNESDAY_PM,
c_rec.THURSDAY_AM,
c_rec.THURSDAY_PM,
c_rec.FRIDAY_AM,
c_rec.FRIDAY_PM,
c_rec.SATURDAY_AM,
c_rec.TEMP_REGISTRATION_STATUS,
c_rec.DATE_RECEIVED,
c_rec.TEMPSTATUS);

end loop;
end;?
--Transforming
--REPLACING ALL NULLS
UPDATE ST_TEMP SET TITLE = '0' WHERE  TITLE IS NULL;
UPDATE ST_TEMP SET FIRST_NAME = 'N/A' WHERE  FIRST_NAME IS NULL;
UPDATE ST_TEMP SET TEL_HOME = '00000000000' WHERE  TEL_HOME IS NULL;
UPDATE ST_TEMP SET FAX_HOME = '00000000000' WHERE  FAX_HOME IS NULL;
UPDATE ST_TEMP SET TEL_WORK = '00000000000' WHERE  TEL_WORK IS NULL;
UPDATE ST_TEMP SET FAX_WORK = '00000000000' WHERE  FAX_WORK IS NULL;
UPDATE ST_TEMP SET MOBILE_PHONE = '00000000000' WHERE  MOBILE_PHONE IS NULL;
UPDATE ST_TEMP SET GENDER = REPLACE(GENDER,'1','Female');
UPDATE ST_TEMP SET GENDER = REPLACE(GENDER,'2','Male');
UPDATE ST_TEMP SET GENDER = REPLACE(GENDER,'0','Not Known');
UPDATE ST_TEMP SET GENDER = REPLACE(GENDER,'','Not Known');
UPDATE ST_TEMP SET GENDER = 'Not Known' WHERE  GENDER IS NULL;
UPDATE ST_TEMP SET DATE_OF_BIRTH = '01/12/2000' WHERE  DATE_OF_BIRTH IS NULL;
--CHANGING NATIONALITY
UPDATE ST_TEMP SET NATIONALITY = REPLACE(NATIONALITY,'1','British');
UPDATE ST_TEMP SET NATIONALITY = REPLACE(NATIONALITY,'2','Irish');
UPDATE ST_TEMP SET NATIONALITY = REPLACE(NATIONALITY,'5','African');
UPDATE ST_TEMP SET NATIONALITY = REPLACE(NATIONALITY,'7','Not Known');
UPDATE ST_TEMP SET NATIONALITY = REPLACE(NATIONALITY,'3', 'Not Known');
UPDATE ST_TEMP SET NATIONALITY = REPLACE(NATIONALITY,'4', 'Not Known');
UPDATE ST_TEMP SET NATIONALITY = REPLACE(NATIONALITY,'10', 'European');
UPDATE ST_TEMP SET NATIONALITY = REPLACE(NATIONALITY,'13', 'Indian');
UPDATE ST_TEMP SET NATIONALITY = REPLACE(NATIONALITY,'9', 'South Africa');
UPDATE ST_TEMP SET NATIONALITY = 'Not Known' WHERE  NATIONALITY IS NULL;
--CHANGING CAR
UPDATE ST_TEMP SET USE_OF_A_CAR = REPLACE(USE_OF_A_CAR,'0', 'No');
UPDATE ST_TEMP SET USE_OF_A_CAR = REPLACE(USE_OF_A_CAR,'1', 'Yes');


--CHANGING QUALIFCIATION NULL
UPDATE ST_TEMP SET QUALIFICATION_YEAR = '0000' WHERE  QUALIFICATION_YEAR IS NULL;
UPDATE ST_TEMP SET QUALIFICATION_PLACE = 'Not Known' WHERE  QUALIFICATION_PLACE IS NULL;
--REPLACING NULLS IN TIMETABLE
UPDATE ST_TEMP SET MONDAY_AM = REPLACE(MONDAY_AM,'1', 'Yes');
UPDATE ST_TEMP SET MONDAY_PM = REPLACE(MONDAY_PM,'1', 'Yes');
UPDATE ST_TEMP SET TUESDAY_AM = REPLACE(TUESDAY_AM,'1', 'Yes');
UPDATE ST_TEMP SET TUESDAY_PM = REPLACE(TUESDAY_PM,'1', 'Yes');
UPDATE ST_TEMP SET WEDNESDAY_AM = REPLACE(WEDNESDAY_AM,'1', 'Yes');
UPDATE ST_TEMP SET WEDNESDAY_PM = REPLACE(WEDNESDAY_PM,'1', 'Yes');
UPDATE ST_TEMP SET THURSDAY_AM = REPLACE(THURSDAY_AM,'1', 'Yes');
UPDATE ST_TEMP SET THURSDAY_PM = REPLACE(THURSDAY_PM,'1', 'Yes');
UPDATE ST_TEMP SET FRIDAY_AM = REPLACE(FRIDAY_AM,'1', 'Yes');
UPDATE ST_TEMP SET FRIDAY_PM = REPLACE(FRIDAY_PM,'1', 'Yes');
UPDATE ST_TEMP SET SATURDAY_AM = REPLACE(SATURDAY_AM,'1', 'Yes');
UPDATE ST_TEMP SET MONDAY_AM = REPLACE(MONDAY_AM,'0', 'No');
UPDATE ST_TEMP SET MONDAY_PM = REPLACE(MONDAY_PM,'0', 'No');
UPDATE ST_TEMP SET TUESDAY_AM = REPLACE(TUESDAY_AM,'0', 'No');
UPDATE ST_TEMP SET TUESDAY_PM = REPLACE(TUESDAY_PM,'0', 'No');
UPDATE ST_TEMP SET WEDNESDAY_AM = REPLACE(WEDNESDAY_AM,'0', 'No');
UPDATE ST_TEMP SET WEDNESDAY_PM = REPLACE(WEDNESDAY_PM,'0', 'No');
UPDATE ST_TEMP SET THURSDAY_AM = REPLACE(THURSDAY_AM,'0', 'No');
UPDATE ST_TEMP SET THURSDAY_PM = REPLACE(THURSDAY_PM,'0', 'No');
UPDATE ST_TEMP SET FRIDAY_AM = REPLACE(FRIDAY_AM,'0', 'No');
UPDATE ST_TEMP SET FRIDAY_PM = REPLACE(FRIDAY_PM,'0', 'No');
UPDATE ST_TEMP SET SATURDAY_AM = REPLACE(SATURDAY_AM,'0', 'No');
UPDATE ST_TEMP SET ADDRESS_LINE_1 = REPLACE(ADDRESS_LINE_1,'''', '');
--UPDATING ADDRESS STATEMENTS GOT TOO LONG HENCE I DID NOT ADD IT IN HERE


--REPLACING ALL NULLS IN ADDRESS
UPDATE ST_TEMP SET ADDRESS_LINE_1 = 'Not Known' WHERE  ADDRESS_LINE_1 IS NULL;
UPDATE ST_TEMP SET ADDRESS_LINE_2 = 'Not Known' WHERE  ADDRESS_LINE_2 IS NULL;
UPDATE ST_TEMP SET TOWN = 'Not Known' WHERE  TOWN IS NULL;
UPDATE ST_TEMP SET COUNTY = 'Not Known' WHERE  COUNTY IS NULL;
UPDATE ST_TEMP SET POSTCODE = 'N/A' WHERE  POSTCODE IS NULL;
--CHANGING CURRENT STATUS
UPDATE DW_TEMP SET CURRENT_STATUS = REPLACE(CURRENT_STATUS,'0','Not Known');
UPDATE DW_TEMP SET CURRENT_STATUS = REPLACE(CURRENT_STATUS,'7.0,'Other');
UPDATE DW_TEMP SET CURRENT_STATUS = REPLACE(CURRENT_STATUS,'6.0,'Retired');
UPDATE DW_TEMP SET CURRENT_STATUS = REPLACE(CURRENT_STATUS,'3.0','Assistant');
UPDATE DW_TEMP SET CURRENT_STATUS = REPLACE(CURRENT_STATUS,'1.0','Principal Full-Time');
UPDATE DW_TEMP SET CURRENT_STATUS = REPLACE(CURRENT_STATUS,'5.0','Retainer');
UPDATE DW_TEMP SET CURRENT_STATUS = REPLACE(CURRENT_STATUS,'4.0','Temporary');
UPDATE DW_TEMP SET CURRENT_STATUS = REPLACE(CURRENT_STATUS,'2.0','Principal Part-Time');
--CHANGING TYPE OF COVER
UPDATE DW_TEMP SET TYPE_OF_COVER_PREFERRED = REPLACE(TYPE_OF_COVER_PREFERRED,'0','Not Known');
UPDATE DW_TEMP SET TYPE_OF_COVER_PREFERRED = REPLACE(TYPE_OF_COVER_PREFERRED,'3.0','Window Dresser');
UPDATE DW_TEMP SET TYPE_OF_COVER_PREFERRED = REPLACE(TYPE_OF_COVER_PREFERRED,'1.0','Shop Assistant');
UPDATE DW_TEMP SET TYPE_OF_COVER_PREFERRED = REPLACE(TYPE_OF_COVER_PREFERRED,'4.0','Stores Assistant');
UPDATE DW_TEMP SET TYPE_OF_COVER_PREFERRED = REPLACE(TYPE_OF_COVER_PREFERRED,'2.0','Floor Manager');
--CHANGING REGISTRATION STATUS
ALTER TABLE DW_TEMP MODIFY TEMP_REGISTRATION_STATUS VARCHAR(30);
UPDATE DW_TEMP SET TEMP_REGISTRATION_STATUS = REPLACE(TEMP_REGISTRATION_STATUS,'0','Not Known');
UPDATE DW_TEMP SET TEMP_REGISTRATION_STATUS = REPLACE(TEMP_REGISTRATION_STATUS,'14','None');
UPDATE DW_TEMP SET TEMP_REGISTRATION_STATUS = REPLACE(TEMP_REGISTRATION_STATUS,'6.0','Waiting for a decision');
UPDATE DW_TEMP SET TEMP_REGISTRATION_STATUS = REPLACE(TEMP_REGISTRATION_STATUS,'5.0','Waiting for Both References');
UPDATE DW_TEMP SET TEMP_REGISTRATION_STATUS = REPLACE(TEMP_REGISTRATION_STATUS,'4.0','Waiting for 1 Reference');
UPDATE DW_TEMP SET TEMP_REGISTRATION_STATUS = REPLACE(TEMP_REGISTRATION_STATUS,'1.0','Waiting for Application Form');
--CHANGING TEMP STATUS
UPDATE DW_TEMP SET TEMPSTATUS = REPLACE(TEMPSTATUS,'1.0','Live');
UPDATE DW_TEMP SET TEMPSTATUS = REPLACE(TEMPSTATUS,'2.0','Archive');
UPDATE DW_TEMP SET TEMPSTATUS = REPLACE(TEMPSTATUS,'0','Not Known');
--DEFAULT SETTINGS
ALTER TABLE DW_TEMP MODIFY ADDRESS_LINE_1 DEFAULT 'Not Known';
ALTER TABLE DW_TEMP MODIFY ADDRESS_LINE_2 DEFAULT 'Not Known';
ALTER TABLE DW_TEMP MODIFY TOWN DEFAULT 'Not Known';
ALTER TABLE DW_TEMP MODIFY COUNTY DEFAULT 'Not Known';
ALTER TABLE DW_TEMP MODIFY GENDER DEFAULT 'Not Known';
ALTER TABLE DW_TEMP MODIFY CURRENT_STATUS DEFAULT 'Not Known';
ALTER TABLE DW_TEMP MODIFY NATIONALITY DEFAULT 'Not Known';
ALTER TABLE DW_TEMP MODIFY QUALIFICATION_PLACE DEFAULT 'Not Known';
ALTER TABLE DW_TEMP MODIFY TYPE_OF_COVER_PREFERRED DEFAULT 'Not Known';
ALTER TABLE DW_TEMP MODIFY TEMP_REGISTRATION_STATUS DEFAULT 'Not Known';
ALTER TABLE DW_TEMP MODIFY TEMPSTATUS DEFAULT 'Not Known';
ALTER TABLE DW_TEMP MODIFY FIRST_NAME DEFAULT 'N/A';
ALTER TABLE DW_TEMP MODIFY LAST_NAME DEFAULT 'N/A';
ALTER TABLE DW_TEMP MODIFY POSTCODE DEFAULT 'N/A';
ALTER TABLE DW_TEMP MODIFY TEL_HOME DEFAULT '00000000000';
ALTER TABLE DW_TEMP MODIFY FAX_HOME DEFAULT '00000000000';
ALTER TABLE DW_TEMP MODIFY TEL_WORK DEFAULT '00000000000';
ALTER TABLE DW_TEMP MODIFY FAX_WORK DEFAULT '00000000000';
ALTER TABLE DW_TEMP MODIFY MOBILE_PHONE DEFAULT '00000000000';
ALTER TABLE DW_TEMP MODIFY MONDAY_AM DEFAULT 'No';
ALTER TABLE DW_TEMP MODIFY MONDAY_PM DEFAULT 'No';
ALTER TABLE DW_TEMP MODIFY TUESDAY_AM DEFAULT 'No';
ALTER TABLE DW_TEMP MODIFY TUESDAY_PM DEFAULT 'No';
ALTER TABLE DW_TEMP MODIFY WEDNESDAY_AM DEFAULT 'No';
ALTER TABLE DW_TEMP MODIFY WEDNESDAY_PM DEFAULT 'No';
ALTER TABLE DW_TEMP MODIFY THURSDAY_AM DEFAULT 'No';
ALTER TABLE DW_TEMP MODIFY THURSDAY_PM DEFAULT 'No';
ALTER TABLE DW_TEMP MODIFY FRIDAY_AM DEFAULT 'No';
ALTER TABLE DW_TEMP MODIFY FRIDAY_PM DEFAULT 'No';
ALTER TABLE DW_TEMP MODIFY SATURDAY_AM DEFAULT 'No';
ALTER TABLE DW_TEMP MODIFY APP_RECEIVED DEFAULT '01/12/2000';
--EMAIL NULL
UPDATE DW_TEMP SET EMAIL = 'Not Known' WHERE  EMAIL IS NULL;
--UPDATING TITLE
UPDATE DW_TEMP SET TITLE = REPLACE(TITLE,'0','Ms') WHERE GENDER = 'Female';
UPDATE DW_TEMP SET TITLE = REPLACE(TITLE,'0','Mr') WHERE GENDER = 'Male';
