--TABLE: DW_SESSION
--CLEANSING IN PREPARATION OF FACT TABLE
--Creating table
CREATE TABLE DW_SESSION(
SESSIONID INT NOT NULL,
REQUESTID INT NOT NULL,
TEMPID INT NOT NULL,
SESSIONDATE VARCHAR(20) NOT NULL,
SESSIONSTART VARCHAR(20) NOT NULL,
SESSIONEND VARCHAR(20) NOT NULL,
STATUS VARCHAR(20) NOT NULL,
TYPE VARCHAR(20) NOT NULL,
EMPLOYEECOVERED INT NOT NULL,
DOPRINT VARCHAR(3) NOT NULL,
PRIMARY KEY(SESSIONID)
);
--Transferring
declare
Cursor c_client is
SELECT SESSIONID,
REQUESTID,
TEMPID,
SESSIONDATE,
SESSIONSTART,
SESSIONEND,
STATUS,
TYPE,
EMPLOYEECOVERED,
DOPRINT from ST_SESSION;
begin
for c_rec in c_client loop
insert into DW_SESSION values(c_rec.SESSIONID, c_rec.REQUESTID, c_rec.TEMPID, c_rec.SESSIONDATE, c_rec.SESSIONSTART, c_rec.SESSIONEND, c_rec.STATUS, c_rec.TYPE, c_rec.EMPLOYEECOVERED, c_rec.DOPRINT);

end loop;
end;?
--Transforming
--CHANGING ALL NULLS
UPDATE ST_SESSION SET TEMPID = '0' WHERE  TEMPID IS NULL;
UPDATE ST_SESSION SET EMPLOYEECOVERED = '0' WHERE  EMPLOYEECOVERED IS NULL;
UPDATE ST_SESSION SET DOPRINT = REPLACE(DOPRINT,'1','Yes');
UPDATE ST_SESSION SET DOPRINT = REPLACE(DOPRINT,'0','No');
UPDATE ST_SESSION SET SESSIONSTART = '00:00:00' WHERE  SESSIONSTART IS NULL;
UPDATE ST_SESSION SET SESSIONEND = '00:00:00' WHERE  SESSIONEND IS NULL;

--DEFAULT SETTINGS
ALTER TABLE DW_SESSION
MODIFY EMPLOYEECOVERED DEFAULT '0';
ALTER TABLE DW_SESSION
MODIFY DOPRINT DEFAULT 'No';
ALTER TABLE DW_SESSION
MODIFY SESSIONSTART DEFAULT '00:00:00';
ALTER TABLE DW_SESSION
MODIFY SESSIONEND DEFAULT '00:00:00';
--CHANGING TYPE
UPDATE DW_SESSION SET TYPE = REPLACE(TYPE,'6','Cashier');
UPDATE DW_SESSION SET TYPE = REPLACE(TYPE,'4','Store Assistant');
UPDATE DW_SESSION SET TYPE = REPLACE(TYPE,'3','Window Dresser');
UPDATE DW_SESSION SET TYPE = REPLACE(TYPE,'2','Floor Manager');
UPDATE DW_SESSION SET TYPE = REPLACE(TYPE,'1','Shop Assistant');
UPDATE DW_SESSION SET TYPE = REPLACE(TYPE,'0','Not Known');
--CAPITAL LETTERS TO STATUS
UPDATE DW_FACT_TABLE SET STATUS = initcap(STATUS);
