DROP TABLE DW_LOCAL_COUNCIL; --was used to recreate if had any issues when populating
--Creating Table
create table DW_LOCAL_COUNCIL (
LOCALCOUNCIL_ID INT NOT NULL,
LOCALCOUNCILNAME VARCHAR(255) NOT NULL,
ADDRESS VARCHAR(255) NOT NULL,
TOWN VARCHAR(255) NOT NULL,
COUNTY VARCHAR(255) NOT NULL,
POSTCODE VARCHAR(255) NOT NULL,
TELEPHONE VARCHAR(14) NOT NULL,
FAX VARCHAR(14) NOT NULL,
APPROXIMATE_LIST_SIZE INT NOT NULL,
TYPE_OF_COMPUTER_SYSTEM VARCHAR(80) NOT NULL,
COMPUTER_USED_IN_CONSULTATIONS VARCHAR(10) NOT NULL,
APPOINTMENT_SYSTEM INT NOT NULL,
LEAFLETS VARCHAR(10) NOT NULL,
TYPE_OF_LOCAL_COUNCIL NUMBER(38) NOT NULL,
PRIMARY KEY(LOCALCOUNCIL_ID)
);

--populating
declare
Cursor c_client is

SELECT LOCALCOUNCIL_ID, LOCALCOUNCILNAME, ADDRESS_LINES_1, ADDRESS_LINE_2, TOWN, COUNTY, POSTCODE, TELEPHONE, FAX,
APPROXIMATE_LIST_SIZE, TYPE_OF_COMPUTER_SYSTEM, COMPUTER_USED_IN_CONSULTATIONS, APPOINTMENT_SYSTEM, LEAFLETS, TYPEOFLOCALCOUNCIL from LOCAL_COUNCIL;

begin
for c_rec in c_client loop
insert into DW_LOCAL_COUNCIL values(c_rec.LOCALCOUNCIL_ID, c_rec.LOCALCOUNCILNAME, c_rec.ADDRESS_LINES_1 || ' ' ||  c_rec.ADDRESS_LINE_2, c_rec.TOWN, c_rec.COUNTY, 
c_rec.POSTCODE, c_rec.TELEPHONE, c_rec.FAX, c_rec.APPROXIMATE_LIST_SIZE, c_rec.TYPE_OF_COMPUTER_SYSTEM, c_rec.COMPUTER_USED_IN_CONSULTATIONS, c_rec.APPOINTMENT_SYSTEM, c_rec.LEAFLETS, c_rec.TYPEOFLOCALCOUNCIL);
end loop;
end;

--ALTERING DATA TYPE
ALTER TABLE LOCAL_COUNCIL MODIFY TYPE_OF_COMPUTER_SYSTEM VARCHAR(80);
--UPDATING TYPE OF CS
UPDATE LOCAL_COUNCIL SET TYPE_OF_COMPUTER_SYSTEM = REPLACE(TYPE_OF_COMPUTER_SYSTEM,'4','Other');
UPDATE LOCAL_COUNCIL SET TYPE_OF_COMPUTER_SYSTEM = REPLACE(TYPE_OF_COMPUTER_SYSTEM,'5','VAMP');
UPDATE LOCAL_COUNCIL SET TYPE_OF_COMPUTER_SYSTEM = REPLACE(TYPE_OF_COMPUTER_SYSTEM,'6','Meditel');
UPDATE LOCAL_COUNCIL SET TYPE_OF_COMPUTER_SYSTEM = REPLACE(TYPE_OF_COMPUTER_SYSTEM,'7','Micro Solutions GP Plus');
UPDATE LOCAL_COUNCIL SET TYPE_OF_COMPUTER_SYSTEM = REPLACE(TYPE_OF_COMPUTER_SYSTEM,'9','EMIS');
UPDATE LOCAL_COUNCIL SET TYPE_OF_COMPUTER_SYSTEM = REPLACE(TYPE_OF_COMPUTER_SYSTEM,'14','GP Exeter');
UPDATE LOCAL_COUNCIL SET TYPE_OF_COMPUTER_SYSTEM = REPLACE(TYPE_OF_COMPUTER_SYSTEM,'12','Seetec');
--DELETE EMPTY ROW
DELETE FROM local_council WHERE LOCALCOUNCIL_ID = '57';
--UPDATING CONS TO YES OR NO
UPDATE LOCAL_COUNCIL SET COMPUTER_USED_IN_CONSULTATIONS = REPLACE(COMPUTER_USED_IN_CONSULTATIONS,'0',’No’);
UPDATE LOCAL_COUNCIL SET COMPUTER_USED_IN_CONSULTATIONS = REPLACE(COMPUTER_USED_IN_CONSULTATIONS,'1','Yes');
--UPDATING LEAFLETS
UPDATE LOCAL_COUNCIL SET LEAFLETS = REPLACE(LEAFLETS,'1','Yes');
UPDATE LOCAL_COUNCIL SET LEAFLETS = REPLACE(LEAFLETS,'2',No);
--FIXING ADDRESS
--UPDATING ADDRESS STATEMENTS GOT TOO LONG HENCE I DID NOT ADD IT IN HERE
UPDATE LOCAL_COUNCIL SET TOWN = 'Bromley' WHERE TOWN = '13 Ravensbourne Road' AND LOCALCOUNCILNAME = '13 Ravensbourne Road';
UPDATE LOCAL_COUNCIL SET LOCALCOUNCILNAME = 'Bromley' WHERE TOWN = 'Bromley' AND LOCALCOUNCILNAME = '13 Ravensbourne Road';
Update Local_Council Set County = 'Kent' Where Address_Lines_1 = '13 Ravensbourne Road';
Update Local_Council Set County = 'Kent' Where Address_Lines_1 = '27 Brook Lane';
UPDATE LOCAL_COUNCIL SET COUNTY = 'Kent' WHERE localcouncil_id = '60';
UPDATE LOCAL_COUNCIL SET TOWN = 'Beckenham' WHERE localcouncil_id = '60';
UPDATE LOCAL_COUNCIL SET ADDRESS_LINE_2 = '' WHERE localcouncil_id = '60';
UPDATE LOCAL_COUNCIL SET localcouncilname = 'Beckenham' WHERE localcouncil_id = '60';
UPDATE LOCAL_COUNCIL SET COUNTY = 'Kent' WHERE localcouncil_id = '62';
UPDATE LOCAL_COUNCIL SET COUNTY = 'Kent' WHERE localcouncil_id = '63';
UPDATE LOCAL_COUNCIL SET TOWN = 'Orpington' WHERE localcouncil_id = '62';
UPDATE LOCAL_COUNCIL SET TOWN = 'Orpington' WHERE localcouncil_id = '63';
UPDATE LOCAL_COUNCIL SET ADDRESS_LINE_2 = '' WHERE localcouncil_id = '62';
UPDATE LOCAL_COUNCIL SET ADDRESS_LINE_2 = '' WHERE localcouncil_id = '63';
UPDATE LOCAL_COUNCIL SET LOCALCOUNCILNAME = 'Orpington' WHERE localcouncil_id = '62';
UPDATE LOCAL_COUNCIL SET LOCALCOUNCILNAME = 'Orpington' WHERE localcouncil_id = '63';
UPDATE LOCAL_COUNCIL SET TOWN = 'Bromley' WHERE localcouncil_id = '58';
UPDATE LOCAL_COUNCIL SET TOWN = 'Orpington' WHERE localcouncil_id = '59';
UPDATE LOCAL_COUNCIL SET ADDRESS_LINE_2 = '' WHERE localcouncil_id = '58';
UPDATE LOCAL_COUNCIL SET ADDRESS_LINE_2 = '' WHERE localcouncil_id = '59';
UPDATE LOCAL_COUNCIL SET LOCALCOUNCILNAME  = 'Bromley' WHERE localcouncil_id = '58';
UPDATE LOCAL_COUNCIL SET LOCALCOUNCILNAME  = 'Orpington' WHERE localcouncil_id = '59';
UPDATE LOCAL_COUNCIL SET localcouncilname = 'Penge' WHERE localcouncil_id = '40';
UPDATE LOCAL_COUNCIL SET TOWN = 'Penge' WHERE localcouncil_id = '40';
--FIXING DEFAULT
UPDATE DW_LOCAL_COUNCIL SET APPROXIMATE_LIST_SIZE = '0000' WHERE  APPROXIMATE_LIST_SIZE IS NULL;
UPDATE DW_LOCAL_COUNCIL SET ADDRESS = 'N/A' WHERE  ADDRESS IS NULL;
UPDATE DW_LOCAL_COUNCIL SET FAX = `0` WHERE  ADDRESS IS NULL;

--DEFAULT SETTING
ALTER TABLE DW_LOCAL_COUNCIL MODIFY ADDRESS DEFAULT 'N/A';
ALTER TABLE DW_LOCAL_COUNCIL MODIFY ADDRESS NOT NULL;
ALTER TABLE DW_LOCAL_COUNCIL MODIFY FAX DEFAULT '0';
ALTER TABLE DW_LOCAL_COUNCIL MODIFY TOWN DEFAULT 'N/A';
ALTER TABLE DW_LOCAL_COUNCIL MODIFY COUNTY DEFAULT 'N/A';
ALTER TABLE DW_LOCAL_COUNCIL MODIFY POSTCODE DEFAULT 'N/A';
ALTER TABLE DW_LOCAL_COUNCIL MODIFY TELEPHONE DEFAULT '0';
ALTER TABLE DW_LOCAL_COUNCIL MODIFY APPROXIMATE_LIST_SIZE DEFAULT '0';
ALTER TABLE DW_LOCAL_COUNCIL MODIFY TYPE_OF_COMPUTER_SYSTEM DEFAULT 'Not Known';
ALTER TABLE DW_LOCAL_COUNCIL MODIFY COMPUTER_USED_IN_CONSULTATIONS DEFAULT 'No';
ALTER TABLE DW_LOCAL_COUNCIL MODIFY APPOINTMENT_SYSTEM DEFAULT '0';
ALTER TABLE DW_LOCAL_COUNCIL MODIFY LEAFLETS DEFAULT 'No';
ALTER TABLE DW_LOCAL_COUNCIL MODIFY TYPE_OF_LOCAL_COUNCIL DEFAULT '0';