--create table for employee dimension
create table DW_EMPLOYEE_DETAILS (
EMPLOYEE_ID INT NOT NULL,
LOCAL_COUNCIL_ID INT NOT NULL CONSTRAINT lc_fk REFERENCES DW_LOCAL_COUNCIL(LOCALCOUNCIL_ID),
TITLE VARCHAR(10) NOT NULL,
FULL_NAME VARCHAR(60) NOT NULL,
CURRENT_STATUS VARCHAR(40) NOT NULL,
YEAR_QUALIFIED INT DEFAULT(0000) NOT NULL,
PRIMARY KEY(EMPLOYEE_ID)
);

--populating employee details
declare
Cursor c_client is

select EMPLOYEE_ID, LOCALCOUNCIL_ID, TITLE, FIRST_NAME, LAST_NAME, CURRENT_STATUS_ID, YEAR_QUALIFIED, INITIALS, SHOW, DELETED
from EMPLOYEE_DETAILS;

begin
for c_rec in c_client loop
insert into DW_EMPLOYEE_DETAILS values(c_rec.EMPLOYEE_ID, c_rec.LOCALCOUNCIL_ID, c_rec.TITLE, c_rec.FIRST_NAME || ' ' || c_rec.LAST_NAME, c_rec.CURRENT_STATUS_ID, c_rec.YEAR_QUALIFIED);

end loop;
end;


--Transforming
--Title Replace
UPDATE EMPLOYEE_DETAILS SET TITLE = REPLACE(TITLE,'1','Dr');
UPDATE EMPLOYEE_DETAILS SET TITLE = REPLACE(TITLE,'2','Mr');
UPDATE EMPLOYEE_DETAILS SET TITLE = REPLACE(TITLE,'3','Miss');
UPDATE EMPLOYEE_DETAILS SET TITLE = REPLACE(TITLE,'4','Ms');
UPDATE EMPLOYEE_DETAILS SET CURRENT_STATUS_ID = REPLACE(CURRENT_STATUS_ID,'5',Retainer);

--Current Status Replace
--Changing CURRENT STATUS to 40 Bytes
ALTER TABLE EMPLOYEE_DETAILS MODIFY CURRENT_STATUS_ID VARCHAR(40);
UPDATE EMPLOYEE_DETAILS SET CURRENT_STATUS_ID = REPLACE(CURRENT_STATUS_ID,'3','Assistant');
UPDATE EMPLOYEE_DETAILS SET CURRENT_STATUS_ID = REPLACE(CURRENT_STATUS_ID,'8','Not Known');
UPDATE EMPLOYEE_DETAILS SET CURRENT_STATUS_ID = REPLACE(CURRENT_STATUS_ID,'4','Temporary');
UPDATE EMPLOYEE_DETAILS SET CURRENT_STATUS_ID = REPLACE(CURRENT_STATUS_ID,'1','Principal Full-Time');
UPDATE EMPLOYEE_DETAILS SET CURRENT_STATUS_ID = REPLACE(CURRENT_STATUS_ID,'6','Retired');

--Assumptions
UPDATE EMPLOYEE_DETAILS SET CURRENT_STATUS_ID = REPLACE(CURRENT_STATUS_ID,'9','Other');
UPDATE EMPLOYEE_DETAILS SET CURRENT_STATUS_ID = REPLACE(CURRENT_STATUS_ID,'0','Not Known');
UPDATE EMPLOYEE_DETAILS SET CURRENT_STATUS_ID = 'Not Known' WHERE CURRENT_STATUS_ID IS NULL;


--REMOVING NOT NULL EMPLOYEE_DETAILS
UPDATE EMPLOYEE_DETAILS SET YEAR_QUALIFIED = '0000' WHERE  YEAR_QUALIFIED IS NULL;
UPDATE CAREPROVIDER_COMPUTER_SYSTEM SET COMPUTERSYSTEMDESCRIPTION = 'Empty' WHERE  COMPUTERSYSTEMDESCRIPTION IS NULL;
UPDATE EMPLOYEE_DETAILS SET FIRST_NAME = concat(FIRST_NAME, '.');

--Changing to Capital Name
UPDATE employee_details SET FIRST_NAME = initcap(FIRST_NAME);
UPDATE employee_details SET LAST_NAME= initcap(LAST_NAME);

--FIND ALL NULL WITH FIRST NAME AND LAST NAME
SELECT employee_id, LOCALCOUNCIL_ID, FIRST_NAME, LAST_NAME, YEAR_QUALIFIED FROM EMPLOYEE_DETAILS WHERE FIRST_NAME  IS NULL and LAST_NAME IS NULL;
--DELETES WHERE FIRST NAME AND LAST NAME IS NULL
DELETE FROM EMPLOYEE_DETAILS  WHERE FIRST_NAME  IS NULL and LAST_NAME IS NULL;;
--FOREIGN KEYS MATCH
SELECT localcouncil_id FROM EMPLOYEE_DETAILS WHERE localcouncil_id not in (SELECT localcouncil_id from LOCAL_COUNCIL);
--ALTER EMPLOYEE DETAIL TO NUMBER
ALTER TABLE DW_EMPLOYEE_DETAILS MODIFY YEAR_QUALIFIED NUMBER(5);
--VIEW BY ORDER COUNCIL
SELECT LOCAL_COUNCIL_ID, full_name FROM dw_employee_details order by local_council_id asc;
--Default Data
ALTER TABLE DW_EMPLOYEE_DETAILS
MODIFY TITLE DEFAULT 'M.';
ALTER TABLE DW_EMPLOYEE_DETAILS
MODIFY FULL_NAME DEFAULT 'N/A';
ALTER TABLE DW_EMPLOYEE_DETAILS
MODIFY CURRENT_STATUS DEFAULT 'Not Known';
ALTER TABLE DW_EMPLOYEE_DETAILS
MODIFY YEAR_QUALIFIED DEFAULT '0';
