DROP TABLE DW_REFERENCES; --drop table if any issues with populating and recreate table 
--create table
CREATE TABLE DW_REFERENCES(
REFERENCEID INT NOT NULL,
TEMPID INT NOT NULL,
REFEREEID INT NOT NULL CONSTRAINT rf_fk REFERENCES DW_REFEREES_DETAILS(REFEREEID),
DATE_REFERENCE_SENT DATE,
DATE_REFERENCE_RECEIVED DATE,
TELEPHONE_MADE VARCHAR(3) NOT NULL,
PRIMARY KEY(REFERENCEID)
);
--Transferring
declare
Cursor c_client is
SELECT REFERENCEID,
TEMPID,
REFEREEID,
DATE_REFERENCE_SENT,
DATE_REFERENCE_RECEIVED,
TELEPHONE_MADE from ST_REFERENCES;
begin
for c_rec in c_client loop
insert into DW_REFERENCES values(c_rec.REFERENCEID, c_rec.TEMPID, c_rec.REFEREEID, c_rec.DATE_REFERENCE_SENT, c_rec.DATE_REFERENCE_RECEIVED, c_rec.TELEPHONE_MADE);

end loop;
end;



--Transforming
SELECT * FROM ST_REFERENCES WHERE REFEREEID not in (SELECT REFEREEID from DW_REFEREES_DETAILS);
--REFERENCE FOREIGN KEY MATCH
--49-267
--50–268
--51-269
--52-270
--53-271
--54-272
--55-273
--56-274
--57-275
--58-276
--DEFAULT DATA
UPDATE DW_REFERENCES SET DATE_REFERENCE_SENT = '01-DEC-00' WHERE  DATE_REFERENCE_SENT IS NULL;
UPDATE DW_REFERENCES SET DATE_REFERENCE_RECEIVED = '01-DEC-00' WHERE  DATE_REFERENCE_RECEIVED IS NULL;
UPDATE TELEPHONE TO YES/NO
UPDATE DW_REFERENCES SET TELEPHONE_MADE = REPLACE(TELEPHONE_MADE,'0','No');
UPDATE DW_REFERENCES SET TELEPHONE_MADE = REPLACE(TELEPHONE_MADE,'1','Yes');
--ALTER DEFAULT SETTING
ALTER TABLE DW_REFERENCES
MODIFY DATE_REFERENCE_RECEIVED DEFAULT '01-DEC-00';
ALTER TABLE DW_REFERENCES
MODIFY DATE_REFERENCE_SENT DEFAULT '01-DEC-00';
ALTER TABLE DW_REFERENCES
MODIFY TELEPHONE_MADE DEFAULT 'No';
